In [10]:
import tensorflow as tf

tf.random.set_seed(42)

train = tf.random.uniform(shape=[20], minval=-5, maxval=5)

print(train)

tf.Tensor(
[ 1.6456213  -0.58993244 -1.471175   -0.35517454 -4.663396    1.8467236
  2.4011745   3.7244453  -2.7367365  -2.7680314  -1.8961191   2.2233582
 -3.6681283   0.4806385   0.746088    3.9968348  -4.905363    0.21230698
  1.3454447  -3.006717  ], shape=(20,), dtype=float32)


In [32]:
label = tf.greater(train, 0)
label = tf.cast(label, dtype=tf.int64)
print(f"{label=}")

label=<tf.Tensor: shape=(20,), dtype=int64, numpy=
array([1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0],
      dtype=int64)>


In [31]:
max_val = tf.reduce_max(train)
min_val = tf.reduce_min(train)
print(f"{max_val.numpy()=}\t{min_val.numpy()=}\n")

norm_train = tf.squeeze(tf.keras.utils.normalize(train, axis = 0))
print(f"{norm_train=}")

max_val.numpy()=3.9968348	min_val.numpy()=-4.905363

norm_train=<tf.Tensor: shape=(20,), dtype=float32, numpy=
array([ 0.13957603, -0.05003608, -0.12478009, -0.0301247 , -0.39553347,
        0.15663286,  0.2036595 ,  0.31589487, -0.23212074, -0.23477507,
       -0.16082242,  0.18857773, -0.31111825,  0.04076613,  0.06328066,
        0.33899802, -0.4160563 ,  0.01800716,  0.11411607, -0.25501958],
      dtype=float32)>


In [39]:
dataset = tf.data.Dataset.from_tensor_slices((norm_train, tf.cast(label, tf.float32)))
print(f"{list(dataset.as_numpy_iterator())=}")

list(dataset.as_numpy_iterator())=[(0.13957603, 1.0), (-0.050036076, 0.0), (-0.12478009, 0.0), (-0.030124703, 0.0), (-0.39553347, 0.0), (0.15663286, 1.0), (0.2036595, 1.0), (0.31589487, 1.0), (-0.23212074, 0.0), (-0.23477507, 0.0), (-0.16082242, 0.0), (0.18857773, 1.0), (-0.31111825, 0.0), (0.040766135, 1.0), (0.063280664, 1.0), (0.33899802, 1.0), (-0.4160563, 0.0), (0.01800716, 1.0), (0.11411607, 1.0), (-0.25501958, 0.0)]


In [47]:
# With batch size of 4, batch the transformed dataset; then shuffle it
for batch in dataset.batch(4).shuffle(buffer_size=len(dataset)):
    print(f"feature: {batch[0].numpy()}\tlable: {batch[1].numpy()}")

feature: [-0.23212074 -0.23477507 -0.16082242  0.18857773]	lable: [0. 0. 0. 1.]
feature: [ 0.13957603 -0.05003608 -0.12478009 -0.0301247 ]	lable: [1. 0. 0. 0.]
feature: [-0.39553347  0.15663286  0.2036595   0.31589487]	lable: [0. 1. 1. 1.]
feature: [-0.4160563   0.01800716  0.11411607 -0.25501958]	lable: [0. 1. 1. 0.]
feature: [-0.31111825  0.04076613  0.06328066  0.33899802]	lable: [0. 1. 1. 1.]


In [48]:
# Repeat the batched dataset so that each batch will be trained "twice"
for batch in dataset.batch(4).repeat(2).shuffle(buffer_size=len(dataset)):
    print(f"feature: {batch[0].numpy()}\tlable: {batch[1].numpy()}")

feature: [ 0.13957603 -0.05003608 -0.12478009 -0.0301247 ]	lable: [1. 0. 0. 0.]
feature: [-0.23212074 -0.23477507 -0.16082242  0.18857773]	lable: [0. 0. 0. 1.]
feature: [-0.4160563   0.01800716  0.11411607 -0.25501958]	lable: [0. 1. 1. 0.]
feature: [-0.39553347  0.15663286  0.2036595   0.31589487]	lable: [0. 1. 1. 1.]
feature: [-0.31111825  0.04076613  0.06328066  0.33899802]	lable: [0. 1. 1. 1.]
feature: [-0.4160563   0.01800716  0.11411607 -0.25501958]	lable: [0. 1. 1. 0.]
feature: [-0.31111825  0.04076613  0.06328066  0.33899802]	lable: [0. 1. 1. 1.]
feature: [-0.23212074 -0.23477507 -0.16082242  0.18857773]	lable: [0. 0. 0. 1.]
feature: [ 0.13957603 -0.05003608 -0.12478009 -0.0301247 ]	lable: [1. 0. 0. 0.]
feature: [-0.39553347  0.15663286  0.2036595   0.31589487]	lable: [0. 1. 1. 1.]
